import './styles.css';
import Tree from'./Trees.png';
import Mountain from './Mountain.png';



let Home = () => {
    return (
        <>
            <div class="wrapper">
                <header>
                    <img src={Mountain} class="background" alt="why you not work"/>
                    <img src={Tree} class="forground" alt="why you not work"/>
                            <h1 class="title"> Welcome</h1>
                        </header>
                        <section>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure tempore quis ad aut sequi impedit nulla iste eaque nemo quod beatae ut numquam sint autem, architecto porro aspernatur, voluptatibus veniam.
                            Amet quam nobis qui sunt blanditiis ea eos deserunt saepe aperiam dolores. Illum perferendis corrupti tempora nam expedita facilis deserunt, perspiciatis sequi ipsa nihil eum quaerat, veniam, dolorem mollitia voluptatem.
                            Quidem, alias esse tenetur facilis, rem ducimus accusamus ratione, tempora tempore incidunt ipsam blanditiis corporis praesentium nihil! Quae assumenda dolorum ea recusandae, inventore molestiae accusantium obcaecati error sapiente, eaque hic?
                            Iste corrupti, dolore quam maxime mollitia, sequi qui fuga nobis dolores, eligendi sit quod soluta vitae sint ad deleniti magni. Totam culpa natus minus a, vitae necessitatibus repellat distinctio non?
                            Eligendi maiores tenetur officia tempora, perferendis libero? Aspernatur, odio. Tempora est harum cum? Unde voluptatibus, officia sint assumenda veritatis illum, possimus aperiam quae vero voluptatem officiis, similique sit repudiandae incidunt.
                            A nisi tempora cum soluta atque quibusdam quasi ab labore. Ad eius porro quod sequi maiores amet! Fuga libero, unde tempora culpa officiis reiciendis nobis itaque labore assumenda, aliquid cumque?
                            Deleniti, perspiciatis quibusdam assumenda consequatur fuga iure dicta nostrum tempore, amet fugiat animi. Quod aliquid facere libero optio et? Ab culpa esse illum nisi reprehenderit hic similique dolore atque quas.
                            Tempore, dolorem tempora laboriosam doloribus soluta, debitis unde commodi necessitatibus, consequuntur animi quos numquam cumque ab veritatis reiciendis laudantium aspernatur corporis deleniti minima dolore! Architecto deserunt ratione inventore adipisci? Aliquam.
                            Cupiditate voluptatibus ullam a dolor harum amet totam ex aut, pariatur illum nostrum aliquid maiores molestias consequuntur ipsa nemo? Sapiente illum velit earum excepturi ratione nisi. Nesciunt nostrum ut dolorem.
                            Incidunt, quam aliquam? Placeat consequuntur esse dicta et. Ipsam omnis labore tempora vitae dolore laboriosam est at, commodi saepe culpa nesciunt veniam quis corrupti incidunt quaerat consequatur esse, ex suscipit?
                            Maiores rem ratione voluptatem distinctio. Aperiam labore ea autem. Quidem enim deserunt amet necessitatibus. Dolor nulla qui temporibus aspernatur culpa, dicta, sit non nostrum, quod cupiditate nam vitae laudantium! Earum?
                            Accusamus magni quas et porro numquam? Minima unde sed illo adipisci impedit dolorem possimus quis beatae sunt, accusamus nulla excepturi ex inventore debitis. Quasi nemo ipsum voluptates obcaecati, itaque a.
                            Delectus, labore. Ad cum tempore blanditiis, molestias sequi tenetur debitis dolor in ab, dignissimos porro aperiam laborum amet quaerat voluptatibus commodi perferendis, quisquam voluptatum nemo beatae eveniet cumque accusamus minima?
                            Dolorem, labore laudantium dolorum cumque voluptas neque eos suscipit molestias voluptatibus, sit corrupti? Nisi, molestias at eveniet excepturi itaque provident ea magni odit dolor maxime cum nihil esse hic atque!
                            Quia libero eum error eligendi fugit perspiciatis cum ipsum odit at quaerat aliquam, blanditiis aut voluptatem sed temporibus. Reiciendis sed natus tempora, dignissimos non autem omnis voluptas esse dolorum repellendus.
                            Quos itaque reiciendis quod consequuntur sequi nisi velit iste placeat sed beatae? Fugit unde perspiciatis laboriosam officiis esse deserunt nemo suscipit sit incidunt ea amet, porro nobis quas vel eos?
                            Optio illum assumenda sequi nobis ea impedit voluptatum dolorem aliquid odit explicabo, quas ex, recusandae debitis ullam tempora aut fuga dolores ipsam aliquam animi sapiente cumque! Cum esse nemo consequuntur!
                            Blanditiis eum aliquid enim, doloremque odio aperiam voluptatibus pariatur quos eligendi laudantium perspiciatis mollitia beatae omnis, illo earum magni, explicabo reiciendis dolores autem eius cum adipisci totam assumenda. Exercitationem, perferendis.
                            Voluptas voluptate beatae aliquid placeat ea molestiae doloribus, officiis ipsa voluptatem tempora dolorem nulla a doloremque quibusdam qui dicta, temporibus esse. Ipsum aliquam voluptate incidunt ratione soluta. Ullam, consequuntur dolores!
                            Nam, deserunt officiis. Eius, dolores quasi, maiores sint a totam nobis fuga ratione ducimus aliquam cumque laboriosam sit, quos laudantium nisi atque nam repellat eligendi architecto sequi accusamus. Perferendis, fuga.
                            Repellat cupiditate facilis quasi illo quia recusandae voluptas aut, quis libero, saepe quod voluptatem tempora. Dicta totam tempore, veniam iure ut facere eaque repellat excepturi dolore mollitia alias quam cupiditate!
                            Eius enim, placeat fugit necessitatibus iure doloribus perspiciatis possimus harum expedita dicta, quia et provident at. Iure consectetur repellendus est ut. Tempore pariatur totam perferendis, distinctio aspernatur alias suscipit debitis?
                            Nulla temporibus iusto perspiciatis earum ab perferendis nesciunt accusamus adipisci quidem reiciendis fugit nostrum maiores, recusandae est, eligendi saepe? Eum iure natus atque dolorem cupiditate nihil perferendis minus, illo quae?
                            Ipsam saepe officia in mollitia consectetur rerum quisquam iusto aut. Soluta ea sed odit, distinctio optio similique necessitatibus nisi? Omnis, saepe quos voluptatum fuga eligendi id sunt? Error, similique omnis.
                            Aliquid tenetur vitae temporibus omnis voluptate voluptatem dolores ducimus minus repudiandae amet minima ipsam quisquam totam non, quibusdam alias a placeat magni ullam perspiciatis? Hic veritatis ipsam possimus aut animi?
                            Maxime beatae corrupti nam similique. Laboriosam, in nihil! Cupiditate voluptatibus, adipisci rerum debitis aut eligendi fugiat voluptatem eos hic corrupti ea porro, dolores sunt expedita ex! Dicta in sapiente atque.
                            Harum labore numquam recusandae, placeat beatae aut aperiam cum accusantium, perspiciatis quos repellat. Numquam ducimus maxime illum, modi aspernatur nisi deleniti. Consequuntur eaque ipsa dolorem. Accusantium illum obcaecati at tempora.
                            Voluptatem, soluta aperiam odio mollitia velit pariatur quod sapiente autem dolore, tenetur quia inventore ducimus quam voluptatum explicabo ipsum cupiditate illum veniam error quibusdam ut exercitationem distinctio sed. Totam, iusto!
                            Recusandae ratione voluptatum, magnam, blanditiis vitae nisi voluptates similique quis quaerat aperiam id doloribus! Non dicta pariatur accusamus asperiores, similique obcaecati vel cum inventore sunt laboriosam sint, ad corrupti necessitatibus.
                            Reprehenderit magnam porro, rerum assumenda ut commodi iure excepturi mollitia voluptates hic in facere, exercitationem quae a! In, ullam! Facere molestiae maxime maiores saepe quam. Aperiam delectus ex recusandae praesentium.
                            Nam inventore veniam similique, perferendis sapiente aspernatur libero quod, facilis optio suscipit exercitationem eligendi eveniet nisi nemo modi consequatur ullam velit ipsa architecto explicabo repellendus provident id quibusdam. Atque, nobis!
                            Quod molestiae est molestias enim quas dolor amet reiciendis nesciunt, in iusto ab temporibus nemo eveniet deleniti tempora numquam voluptatum! Quae, nam eligendi inventore illum non rem doloremque quos alias?
                            Ea recusandae sit labore quas illo at commodi veritatis saepe est illum, ducimus possimus facilis quia aliquid, provident laboriosam. Aliquam fuga sapiente unde in molestiae! Natus incidunt vitae dicta ipsum.
                            Doloribus similique commodi cumque earum aliquam sunt molestias inventore, dolorem, totam velit rerum minus facilis magnam sapiente quo temporibus harum ratione dolorum voluptate deserunt? Dolor ratione tempora possimus ea distinctio?
                            Tempora ut accusantium maxime numquam vel explicabo dolorem exercitationem sed commodi sint, at cumque impedit doloremque eaque iste unde nisi voluptas, cupiditate ipsum cum alias? Optio ipsum maiores dicta at?
                            Voluptas ipsam accusamus commodi aut voluptatem nobis, repudiandae voluptatibus animi excepturi deleniti adipisci id pariatur libero quod quam sunt exercitationem facere assumenda, sapiente dolorum fuga nisi numquam. Facere, vitae esse.
                            Accusamus, iusto doloremque laudantium exercitationem nam illo adipisci incidunt velit! Ducimus, pariatur nihil cum dicta, eligendi aliquid maiores voluptas quam necessitatibus exercitationem voluptate est, similique eaque ea? Earum, soluta saepe!
                            Consectetur eos odit perspiciatis deserunt earum maiores molestiae fugit id quae debitis expedita minus nisi molestias repudiandae similique non quidem cum ex laboriosam sunt reprehenderit fuga, dolorem aut! Mollitia, expedita.
                            Necessitatibus dolorem mollitia velit accusamus, ipsa illo voluptatum laudantium quis? Repellat, inventore. Porro cupiditate laboriosam quisquam ullam rerum harum, in ut earum, repellendus rem tempora! Dolorum dolores illum accusantium aliquid.
                            At sapiente dicta dignissimos recusandae voluptates temporibus corrupti atque assumenda voluptate ex, error enim veniam quasi aperiam non quis odit possimus necessitatibus! Consectetur assumenda magnam odit, laboriosam officia porro recusandae.
                            Pariatur, facilis. Corrupti delectus dolores quod. In quam officiis, aperiam veniam dicta nulla consequuntur tenetur fugit hic ipsum placeat. Quidem sint voluptatem in aperiam, corrupti sapiente! Praesentium ea ab quaerat.
                            Modi, unde perspiciatis ex asperiores similique nemo temporibus nihil fugit ipsam nostrum possimus omnis tenetur tempora molestiae fugiat, iure quo? Molestiae, dolores autem enim aut quisquam magnam recusandae odio eligendi!
                            Cum, omnis soluta illo labore iusto quasi quibusdam nobis autem, iste nam odit nemo blanditiis veritatis illum consequuntur eligendi impedit velit pariatur rerum ducimus modi aliquam sunt voluptatem dolores. Quos.
                            Quidem voluptatum consequuntur dicta quas! Maxime, ea culpa non magnam aut cupiditate? Velit ex expedita consequatur quae! Quisquam mollitia vero quas nobis, amet temporibus beatae neque dolorem asperiores, esse in.
                            Magni at assumenda pariatur sint perferendis fuga consequuntur aspernatur, ducimus corrupti perspiciatis iure recusandae veritatis non eum libero id! Velit in accusamus aut ipsa sunt autem nihil quidem quasi maiores.
                            Temporibus dolores praesentium maxime? Recusandae labore officiis in aliquam harum porro unde cum eaque. Omnis quidem repellat voluptatem vero, eaque tempora qui laborum asperiores, magni ducimus nisi perferendis rerum sunt.
                            Magnam, ipsa eius rerum perspiciatis saepe aliquam, ut voluptatum accusantium magni reprehenderit ipsam veniam fuga vel! Ducimus, sunt quibusdam! Aperiam sequi natus, consequatur nesciunt pariatur adipisci ab odit facilis quasi!
                            Corrupti aperiam quidem vel expedita reiciendis nostrum enim repudiandae deserunt iusto veritatis dolorum similique, sequi laudantium quos neque praesentium. Debitis sunt esse magni, nihil quas dolorem eum laboriosam soluta iusto!
                            Quod minima, placeat provident repudiandae commodi omnis esse est! Commodi, ullam, excepturi odit alias quis dolorem eaque molestias earum blanditiis quidem in? Temporibus animi fugit quidem quis enim minima ipsa!
                            Inventore, ullam rem asperiores magni iure repellendus harum illum laudantium non cum, quo consectetur. Dolor error, tenetur praesentium voluptate nulla repellendus nemo voluptates laboriosam aut laudantium minus saepe consequatur fugit.
                            Atque deleniti eius cumque obcaecati consectetur amet culpa quibusdam? Quidem enim dolores animi quae error totam, ad veritatis minus ipsam modi quibusdam amet similique ex vero neque impedit ullam at?
                            Pariatur maiores cupiditate laboriosam rerum, doloremque in quas debitis sequi odio. Aspernatur dolorum nihil, sequi totam sunt minima voluptate. Tempora quisquam blanditiis velit vel ad provident non ullam iure cupiditate!
                            Consequuntur ullam pariatur nisi repudiandae nulla facilis quod, similique est harum ipsam, et possimus vel illo, debitis asperiores aspernatur. Totam debitis molestias dicta quibusdam nesciunt in illo? Consequatur, hic dolore!
                            Consequuntur, fugiat ullam velit laborum commodi dolore vero similique expedita veniam reiciendis! Unde vitae minus accusantium odit veniam, consequatur fugit harum dolore sapiente eum facere explicabo autem ipsum rerum atque.
                            Perspiciatis laudantium iure saepe illum iste hic quae reprehenderit, dignissimos doloremque quia architecto natus dolorem amet reiciendis modi facilis totam, explicabo commodi fuga maiores. Culpa nihil sequi optio commodi nisi.
                            Modi tempora, mollitia asperiores tenetur natus dolorem, voluptates aliquid pariatur doloribus vel non praesentium? Alias, veniam adipisci dolorum dolore, perferendis, aspernatur quaerat numquam aliquam commodi doloribus fugit deserunt ex accusantium!
                            Eligendi suscipit nam sit mollitia illum quae, repellendus ut culpa perspiciatis! Earum in, unde consequuntur tempore ducimus a mollitia, consequatur ipsa, ex distinctio natus. Quam nemo dignissimos enim odio qui?
                            Minima, possimus hic! Commodi harum possimus labore consectetur, quaerat modi sit omnis necessitatibus vitae atque similique consequuntur nobis enim minus pariatur, inventore nam alias distinctio autem quia sed. Consectetur, consequuntur.
                            Odio cupiditate perferendis autem nesciunt corrupti. Vitae optio praesentium quasi. Quaerat similique odio deleniti delectus voluptatem? Vero quaerat sapiente alias dolorem est quos at, nisi asperiores neque ea quia aspernatur?
                            Quasi ducimus impedit ullam, doloremque cumque vero molestias temporibus asperiores quia fuga fugit dolorum facere voluptatibus accusamus dolor provident harum ut illo. Expedita in adipisci suscipit dolorem nulla iusto odio!
                            Hic voluptatem assumenda ut numquam saepe at voluptatibus doloribus explicabo dolorum, illum sunt, ea, inventore delectus unde sapiente quidem neque iure laborum expedita aliquid provident porro laboriosam facere. Delectus, repellendus?
                            Delectus, culpa voluptates reprehenderit quod blanditiis voluptas facere odit earum error consectetur recusandae, quam quaerat, exercitationem fugiat quasi accusantium. Velit itaque quisquam, expedita est inventore incidunt voluptatum rerum repellendus veniam?
                            Est nihil ipsum reiciendis totam temporibus praesentium iure quidem recusandae quam quas doloribus dolorem nesciunt, eveniet ducimus error aperiam fuga dolore non consequatur? Debitis soluta pariatur vero cum! Saepe, magni!
                            Repudiandae accusamus eos placeat veniam nemo! Voluptas placeat maiores, nisi fugiat laboriosam officiis saepe officia inventore eveniet culpa corporis asperiores at obcaecati quisquam? Inventore, obcaecati itaque. Quos, saepe quas. Saepe.
                            Iste doloribus repudiandae ut ipsam, amet iure hic. Rerum expedita, beatae ut molestias reiciendis asperiores sapiente cum fugit deleniti rem, voluptates impedit iure totam, nemo similique officia dignissimos? Esse, corrupti?
                            Eius animi dolores debitis qui ratione excepturi laboriosam praesentium in expedita aut? Quos minus reprehenderit soluta unde quas itaque quo, nam voluptatem excepturi odio ipsum numquam ea. Nesciunt, obcaecati autem?
                            Laboriosam possimus saepe qui? Ad repellat optio in nihil praesentium? Placeat reprehenderit ut harum pariatur tempora architecto nostrum quasi voluptatibus voluptatem blanditiis! Voluptates quae, necessitatibus nesciunt molestiae ratione consequatur porro!
                            Impedit dignissimos laudantium harum saepe animi voluptates rerum illum iure, aliquam, quisquam labore voluptate doloribus maiores itaque recusandae numquam deleniti quibusdam unde consequuntur? Tenetur officia deleniti nostrum dicta consequatur nisi!
                            Vitae, nobis dolore. Iusto, nulla! Ab minima est, rem cum ipsam recusandae? Eum, accusamus ad! Vel, praesentium. Enim delectus esse aut aliquid dicta, voluptatem odio aperiam cumque sequi consequatur vero?
                            Deserunt delectus at ullam! Eligendi, minus saepe repellat animi aliquam consequuntur quidem fugit, veritatis quas dolorum quisquam architecto? Excepturi voluptatibus aliquam consequatur qui eos vitae numquam esse nostrum maiores porro?
                            Qui delectus laudantium perspiciatis nulla, deleniti minus unde dolores officiis aut, numquam impedit exercitationem neque corrupti quae eaque necessitatibus id mollitia. Aperiam obcaecati quisquam in autem aspernatur dolore corporis similique.
                            Voluptatibus ipsa expedita temporibus, commodi, sunt, iste quidem eius saepe qui nulla repudiandae numquam et iure officia accusamus doloremque illo autem ratione. Quidem ratione eos laborum provident, quis asperiores dignissimos.
                            Sed est soluta quidem nostrum laborum corporis consequuntur, commodi, ipsum, eum accusamus sapiente. Doloremque dolorem perspiciatis asperiores, molestias facilis placeat ad, voluptate facere vel reiciendis voluptas harum numquam nam in?
                            Velit eum illo laborum! Sit harum ad laborum quaerat vero iusto eveniet molestias voluptas, omnis distinctio sunt, id enim voluptatibus iste vitae fuga natus autem ullam nostrum veniam consectetur sed.
                            Impedit aliquam quasi ipsam quo cum maxime unde, ad voluptatibus aut veniam. Rem vero vitae saepe nesciunt suscipit minus, animi dolorum illo provident, qui corrupti impedit quos, voluptates aut esse?
                            Molestiae pariatur labore adipisci itaque, officiis fugit maxime modi temporibus enim animi esse! Unde enim modi minima. Tempora iste eius iusto, nostrum doloribus atque ipsam sunt repudiandae incidunt, non fugiat!
                            Explicabo nobis natus maiores aut delectus dignissimos alias earum numquam? Veniam sed delectus accusamus. Optio ipsam nostrum voluptates cumque fuga itaque quos earum eum repudiandae aliquid totam, tempore corrupti minus!
                            Beatae voluptas amet rem asperiores ipsum dolores quos earum minus repellat, corrupti quidem saepe animi vel dolorem, magni quaerat quo? Totam provident impedit vero ullam esse. Totam mollitia atque blanditiis.
                            Ratione ipsa temporibus eos error incidunt hic ab libero qui quas ipsum modi dolorem accusamus, recusandae molestiae maiores possimus soluta iste! Provident aperiam modi a deleniti ad assumenda asperiores magni?
                            Incidunt enim voluptas aliquam dignissimos obcaecati, animi excepturi eum eligendi voluptatibus aspernatur veniam sapiente temporibus facere illum eaque aliquid! Qui ea placeat esse. Soluta blanditiis, cupiditate veniam fuga voluptate necessitatibus.
                            Ullam optio dolores veritatis? Est praesentium minima sit consequuntur dicta beatae, expedita, voluptates aliquid veritatis, laborum a deleniti voluptatem magni cum quia ipsam iusto error totam officiis quas dolorem dolore!
                            Delectus in quasi atque amet recusandae similique voluptates harum totam quae reiciendis ad, at id deleniti asperiores beatae unde. Voluptates optio tempore laborum eum voluptatibus excepturi temporibus a. Sit, illum!
                            Reiciendis soluta nobis obcaecati? Velit, vitae, minima animi illo maiores nihil provident nam quam quaerat error amet iste fugit expedita assumenda repellat natus eum ea praesentium maxime eveniet nisi quod?
                            Omnis, possimus? Tenetur dolorem id porro delectus, sed ipsum exercitationem numquam enim quibusdam saepe blanditiis mollitia unde temporibus laborum similique commodi nulla, eum pariatur corrupti perferendis adipisci facere quasi. Doloribus?
                            Ratione dolores praesentium recusandae dignissimos exercitationem esse quos adipisci unde, laborum sapiente sed suscipit perferendis natus enim obcaecati quaerat voluptates debitis! Culpa qui obcaecati voluptatibus soluta, blanditiis voluptas magnam impedit.
                            Recusandae vitae, et possimus consequuntur, alias sapiente fuga libero, dignissimos dolore accusantium quaerat rerum ratione eaque tempora repellendus corporis? Accusamus inventore accusantium praesentium repellendus nostrum, ad recusandae vitae iste atque.
                            Cumque alias blanditiis illo ratione quibusdam exercitationem corporis nesciunt voluptatibus itaque quidem voluptatem sapiente impedit eaque, quasi, inventore earum excepturi nemo, expedita natus modi mollitia! Voluptas est repellat maxime dolores?
                            Reiciendis, blanditiis inventore assumenda quam ducimus, repudiandae repellendus maxime doloremque quaerat alias asperiores sunt cupiditate? Tenetur quas, consectetur sit quae vitae accusamus quos accusantium? Alias veniam ipsum nobis exercitationem ab.
                            Animi aperiam fugiat optio distinctio ut maxime in suscipit ab neque voluptatibus impedit laboriosam eveniet doloremque rem nostrum, ex ratione dolorem quaerat necessitatibus, quasi rerum. Aperiam velit blanditiis error illo?
                            Illo, eligendi temporibus nobis natus nisi sit at corporis! Optio alias autem placeat fugiat nostrum ab tenetur aperiam nemo illo esse quidem recusandae veritatis reiciendis nam debitis, distinctio quasi voluptate.
                            </section>
                    </div>

                </>
                )
}

export default Home;
